//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Details_Sundram
    {
        public int Student_ID { get; set; }
        public int Student_Roll_Number { get; set; }
        public string Student_FirstName { get; set; }
        public string Student_LastName { get; set; }
        public string Student_UniversityName { get; set; }
        public string Student_MailId { get; set; }
        public string Student_Preffered_ProgrammingLanguage { get; set; }
    }
}
